#!/usr/bin/env python
"""
Usage:
  tuyactl <device> color [<r> <g> <b>]
  tuyactl <device> brightness [<brightness>]
  tuyactl <device> temp [<temp>]
  tuyactl <device> switch [<state>]
  tuyactl <device> mode <mode>
  tuyactl <device> scene <scene-no>
  tuyactl <device> white <brightness> <temp>
  tuyactl <device> whiteper <whiteper>
  tuyactl <device> colorper <colorper>
"""

import tinytuya
from docopt import docopt
import os
from pathlib import Path
import configparser
import json

class Device:
    def __init__(self, id, ip, key):
        self.id = id
        self.ip = ip
        self.key = key

class Config:
    devices = {}

    def __init__(self):
        self.paths = [
            Path.home() / ".config" / "tuyactl" / "devices.ini",
            Path("/etc") / "tuyactl" / "devices.ini",
        ]

        xdg_config_home = os.getenv("XDG_CONFIG_HOME")
        if xdg_config_home is not None:
            self.paths.insert(0, Path(xdg_config_home) / "tuyactl" / "devices.ini")

        self.path = self.search_path()

    def search_path(self):
        config_path = None
        for path in self.paths:
            if os.path.exists(path):
                config_path = path

        if config_path is None:
            raise Exception("No config file found")

        self.path = config_path
        return config_path

    def parse(self):
        config = configparser.ConfigParser()
        config.read(self.path)

        for name in config.sections():
            current = config[name]
            self.devices[name] = Device(current["id"], current["ip"], current["key"])

if __name__ == "__main__":
    arguments = docopt(__doc__)
    cfg = Config()
    cfg.parse()
    current = cfg.devices[arguments["<device>"]]
    dev = tinytuya.BulbDevice(current.id, current.ip, current.key)
    dev.set_version(3.3)

    if arguments["switch"]:
        if arguments["<state>"]:
            if arguments["<state>"] == "on":
                dev.turn_on()
            elif arguments["<state>"] == "off":
                dev.turn_off()
            else:
                raise Exception("Switching is only possible with \"on\" or \"off\"")
        else:
            print("on" if dev.state()["is_on"] else "off")          

    if arguments["color"]:
        if not arguments["<r>"] or not arguments["<g>"] or not arguments["<b>"]:
            print(" ".join(tuple(str(i) for i in dev.colour_rgb())))
        else:
            dev.set_colour(int(arguments["<r>"]), int(arguments["<g>"]), int(arguments["<b>"]))

    if arguments["brightness"]:
        if not arguments["brightness"]:
            print(dev.brightness())
        else:
            dev.set_brightness(int(arguments["<brightness>"]))

    if arguments["temp"]:
        if not arguments["brightness"]:
            print(dev.brightness())
        else:
            dev.set_colourtemp(int(arguments["<temp>"]))

    if arguments["white"]:
        dev.set_white(int(arguments["<brightness>"]), int(arguments["<temp>"]))

    if arguments["whiteper"]:
        dev.set_white_percentage(int(arguments["<whiteper>"]))

    if arguments["colorper"]:
        dev.set_colourtemp_percentage(int(arguments["<colorper>"]))

    #Mode and Scene are experimental. Some Features may not apply to your Device.
    if arguments["mode"]:
        dev.set_mode(mode=arguments["<mode>"])

    if arguments["scene"]:
        dev.set_scene(int(arguments["<scene-no>"]))
